Split the oss checklist for libraries and end products
blindnet-io/openness-framework pull request #21
Opened 2022-04-14 15:50 UTC by m4rk055

Split the open source software checklist into 2.  
For now, we distinguish between the two types of software projects:
- libraries (e.g. [blindnet sdk](https://github.com/blindnet-io/blindnet-sdk-js))
- end products (e.g. [blindsend](https://github.com/blindnet-io/blindsend))

Requirements for them differ in certain aspects, like in developer docs.

2022-05-24 14:51 UTC, noelmace approved these changes
LGTM

IMHO, we should proceed with this PR ASAP, and improve it as we go while using it for a first project.

2022-05-24 15:42 UTC, filipblnt requested changes

2022-05-24 15:42 UTC, filipblnt commented on OpenSource/checklists/01-set-up.md
> +## Naming and Presentation
This section is identical as the one below ion line 21 (28), remove this or the other one.

2022-05-24 15:42 UTC, filipblnt commented on OpenSource/checklists/01-set-up.md
>  - [ ] Release process is automated and documented
In Testing section, there's a typo in several bullets -> `Repository include**s**` instead of `include`

2022-05-24 15:42 UTC, filipblnt commented on OpenSource/checklists/01-set-up.md
> +## Naming and Presentation
There is identical section below, remove one

2022-05-25 08:11 UTC, merged

2022-05-25 10:19 UTC, noelmace commented
@m4rk055 avoid merging a PR you created yourself, as it may look like you ignored some feedback. Next time, ping the reviewers on Slack if you feel everything's done and the PR should be merged.