add a README template for DevKit components
blindnet-io/openness-framework pull request #33
Opened 2022-06-20 23:25 UTC by noelmace

- [x] clean the existing template for OSS projects
- [x] add a new "devkit-README.md" template with pre-completed sections to ease the update of all DevKit components' README file

2022-06-20 23:35 UTC, noelmace commented
Would this PR and https://github.com/blindnet-io/sdk-javascript-client/pull/7 be sufficient for @blindnet-io/engineering to update all other READMEs?

2022-06-21 17:06 UTC, m4rk055 requested changes

2022-06-21 17:06 UTC, m4rk055 commented on OpenSource/template/devkit-README.md
> +The blindnet devkit {short-project-name} is available under [MIT](license) (and [here](https://github.com/blindnet-io/openness-framework/blob/main/docs/decision-records/DR-0001-oss-license.md) is why
```suggestion
The blindnet devkit {short-project-name} is available under [MIT][license] (and [here](https://github.com/blindnet-io/openness-framework/blob/main/docs/decision-records/DR-0001-oss-license.md) is why).
```

2022-06-22 06:53 UTC, m4rk055 approved these changes

2022-06-22 11:32 UTC, merged